// proc_reader.cpp
//
// This file does the actual work of opening /proc/<pid>/status and
// /proc/<pid>/stat, reading their text content, and pulling the numbers
// we care about out of them.
//
// Important idea: /proc files are NOT real files on your hard drive. They
// are generated by the Linux kernel the moment you open them, and they
// disappear the moment the process they describe exits. Reading them is
// just as simple as reading a normal text file though, which is why C++'s
// normal file streams (ifstream) work fine here.

#include "proc_reader.h"
#include <fstream>   // ifstream: lets us open and read text files
#include <sstream>   // istringstream: lets us split a line of text into words
#include <unistd.h>  // sysconf: asks the OS for system configuration values

// sysconf(_SC_CLK_TCK) asks the kernel "how many clock ticks make up one
// second on this machine?" We cache the answer in a static variable so we
// only ask once instead of every single time we calculate CPU percent.
long getClockTicksPerSecond() {
    static long ticksPerSecond = sysconf(_SC_CLK_TCK);
    return ticksPerSecond;
}

// Helper: reads /proc/<pid>/status, which looks like this (simplified):
//
//   Name:   sleep
//   State:  S (sleeping)
//   VmPeak:     8192 kB
//   VmRSS:      1024 kB
//   Threads:    1
//
// It is a list of "Label:\tvalue" lines, one per line. We scan line by line
// looking for the labels we care about (VmRSS, VmPeak, Threads) and pull
// the number out of each matching line.
static void readStatusFile(int pid, ProcessSnapshot& snapshot) {
    std::string path = "/proc/" + std::to_string(pid) + "/status";
    std::ifstream file(path);

    if (!file.is_open()) {
        // If we can't open this file, the process has probably exited.
        snapshot.valid = false;
        return;
    }

    std::string line;
    while (std::getline(file, line)) {
        std::istringstream iss(line);
        std::string label;
        iss >> label; // reads the first "word" on the line, e.g. "VmRSS:"

        if (label == "VmRSS:") {
            iss >> snapshot.vmRssKb; // next token on the line is the number
        } else if (label == "VmPeak:") {
            iss >> snapshot.vmPeakKb;
        } else if (label == "Threads:") {
            iss >> snapshot.threadCount;
        }
    }
}

// Helper: reads /proc/<pid>/stat, which is ONE line of space-separated
// values (no labels at all, unlike /status). The fields we want are:
//   field 14 = utime  (CPU ticks spent in user mode)
//   field 15 = stime  (CPU ticks spent in kernel mode)
//
// This file is trickier because field 2 (the process name) is wrapped in
// parentheses and can itself contain spaces, e.g. "(my program)". To handle
// that safely we find the closing parenthesis first and only start counting
// fields after it.
static void readStatFile(int pid, ProcessSnapshot& snapshot) {
    std::string path = "/proc/" + std::to_string(pid) + "/stat";
    std::ifstream file(path);

    if (!file.is_open()) {
        snapshot.valid = false;
        return;
    }

    std::string content;
    std::getline(file, content);

    // Find where the process name (in parentheses) ends, then start
    // reading fields from right after it. This sidesteps the "name has
    // spaces in it" problem entirely.
    size_t closeParen = content.find_last_of(')');
    if (closeParen == std::string::npos) {
        snapshot.valid = false;
        return;
    }

    std::istringstream iss(content.substr(closeParen + 2)); // +2 skips ") "
    std::string field;
    long utime = 0, stime = 0;

    // After the name, field 3 (state) is the first token. utime is the
    // 14th field overall, which is the 12th field after the name, and
    // stime is the 13th field after the name. We just count tokens.
    int fieldIndex = 3; // we resume counting from field 3 (the state field)
    while (iss >> field) {
        if (fieldIndex == 14) {
            utime = std::stol(field);
        } else if (fieldIndex == 15) {
            stime = std::stol(field);
            break; // we have both numbers we need, no reason to keep reading
        }
        fieldIndex++;
    }

    snapshot.utimeTicks = utime;
    snapshot.stimeTicks = stime;
}

ProcessSnapshot readProcessSnapshot(int pid) {
    ProcessSnapshot snapshot{};
    snapshot.valid = true;

    readStatusFile(pid, snapshot);
    if (!snapshot.valid) return snapshot;

    readStatFile(pid, snapshot);
    return snapshot;
}

double calculateCpuPercent(const ProcessSnapshot& previous,
                            const ProcessSnapshot& current,
                            double elapsedSeconds) {
    if (elapsedSeconds <= 0.0) return 0.0;

    // How many CPU ticks were used between the two snapshots.
    long tickDelta = (current.utimeTicks + current.stimeTicks) -
                      (previous.utimeTicks + previous.stimeTicks);

    // Convert ticks to seconds of CPU time actually used.
    double cpuSecondsUsed = static_cast<double>(tickDelta) / getClockTicksPerSecond();

    // CPU percent = (CPU time used / wall clock time passed) * 100.
    // If elapsedSeconds is 0.5s and cpuSecondsUsed is 0.25s, that process
    // used the CPU for half of that window, so 50%.
    return (cpuSecondsUsed / elapsedSeconds) * 100.0;
}
